# Generated by Django 4.2.6 on 2023-10-31 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidateprofile',
            name='bio',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='candidateprofile',
            name='cgpa',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True),
        ),
        migrations.AlterField(
            model_name='candidateprofile',
            name='languages',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='candidateprofile',
            name='major',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='candidateprofile',
            name='university',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
