# Generated by Django 4.2.6 on 2023-10-31 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0002_alter_candidateprofile_bio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidateprofile',
            name='first_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='last_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
