# Generated by Django 4.2.6 on 2023-11-07 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0003_candidateprofile_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidateprofile',
            name='role',
            field=models.CharField(choices=[('candidate', 'Candidate'), ('company', 'Company')], default='candidate', max_length=20),
        ),
    ]
