# Generated by Django 4.2.6 on 2023-10-31 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=150, null=True)),
                ('location', models.CharField(max_length=100, null=True)),
                ('phone', models.CharField(max_length=20, null=True)),
                ('company_email', models.CharField(max_length=50, null=True)),
                ('about', models.TextField(null=True)),
                ('primary_industry', models.CharField(max_length=50, null=True)),
                ('company_size', models.CharField(blank=True, max_length=20, null=True)),
                ('founded_year', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
