# Generated by Django 4.2.6 on 2023-10-31 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_companyprofile_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyprofile',
            name='address',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='website',
            field=models.URLField(blank=True, null=True),
        ),
    ]
